//! Embedded application assets; URL paths match the frontend tree.

use axum::{
    body::Body,
    http::{HeaderMap, HeaderValue, Method, StatusCode, Uri, header},
    response::{IntoResponse, Response},
};
use rust_embed::{EmbeddedFile, RustEmbed};
use sha2::{Digest, Sha256};

#[derive(RustEmbed)]
#[folder = "frontend/"]
#[include = "index.html"]
#[include = "src/**"]
#[include = "views/**"]
#[include = "styles/**"]
#[include = "icons/**"]
#[include = "vendor/**"]
#[exclude = "**/.DS_Store"]
#[exclude = "**/README*"]
#[exclude = "**/*.md"]
#[exclude = "**/*.json"]
#[exclude = "**/LICENSE*"]
#[exclude = "**/REBUILD*"]
#[exclude = "vendor/katex/fonts/*.ttf"]
#[exclude = "vendor/katex/fonts/*.woff"]
#[exclude = "vendor/github-markdown-css/*.css"]
#[exclude = "vendor/cdn-assets/*.css"]
struct FrontendAssets;

/// License texts of the bundled third-party components, generated by
/// `scripts/third-party-notices.mjs`.
const THIRD_PARTY_NOTICES: &[u8] = include_bytes!("../../THIRD_PARTY_NOTICES.md");

pub(crate) async fn serve(method: Method, uri: Uri, headers: HeaderMap) -> Response {
    if method != Method::GET && method != Method::HEAD {
        return (
            StatusCode::METHOD_NOT_ALLOWED,
            [(header::ALLOW, "GET, HEAD")],
        )
            .into_response();
    }
    if uri.path() == "/THIRD_PARTY_NOTICES.md" {
        return notices_response(method == Method::HEAD);
    }
    let mut path = uri.path();
    let mut versioned = false;
    if let Some(rest) = path.strip_prefix("/v/") {
        let Some((version, asset)) = rest.split_once('/') else {
            return StatusCode::NOT_FOUND.into_response();
        };
        if version != crate::build_info::ASSET_VERSION
            || !["src/", "views/", "styles/", "icons/", "vendor/"]
                .iter()
                .any(|prefix| asset.starts_with(prefix))
        {
            return StatusCode::NOT_FOUND.into_response();
        }
        path = &path[(3 + version.len())..];
        versioned = true;
    }
    if path.starts_with("/api/")
        || path == "/api"
        || path.starts_with("/mcp")
        || path.starts_with("/.well-known/")
    {
        return crate::AppError::NotFound {
            resource: "endpoint",
        }
        .into_response();
    }
    if path.contains('\\') || path.split('/').any(|part| part == ".." || part == ".") {
        return StatusCode::NOT_FOUND.into_response();
    }
    let key = path.trim_start_matches('/');
    let asset = FrontendAssets::get(key)
        .map(|file| (file, key))
        .or_else(|| {
            let html_navigation = headers
                .get(header::ACCEPT)
                .and_then(|value| value.to_str().ok())
                .is_some_and(|value| value.contains("text/html"));
            (!versioned
                && (path == "/"
                    || (html_navigation
                        && !key.rsplit('/').next().unwrap_or_default().contains('.'))))
            .then(|| FrontendAssets::get("index.html").map(|file| (file, "index.html")))
            .flatten()
        });
    match asset {
        Some((file, key)) => asset_response(file, key, method == Method::HEAD, &headers, versioned),
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

/// Serves the notices as plain text so browsers show them without rendering.
fn notices_response(head: bool) -> Response {
    let body = if head {
        Body::empty()
    } else {
        Body::from(THIRD_PARTY_NOTICES)
    };
    let mut response = Response::new(body);
    let headers = response.headers_mut();
    headers.insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static("text/plain; charset=utf-8"),
    );
    headers.insert(
        header::CONTENT_LENGTH,
        HeaderValue::from(THIRD_PARTY_NOTICES.len()),
    );
    headers.insert(header::CACHE_CONTROL, HeaderValue::from_static("no-cache"));
    headers.insert(
        header::X_CONTENT_TYPE_OPTIONS,
        HeaderValue::from_static("nosniff"),
    );
    response
}

fn asset_response(
    mut file: EmbeddedFile,
    key: &str,
    head: bool,
    request: &HeaderMap,
    versioned: bool,
) -> Response {
    let etag = if key == "index.html" {
        let prefix = format!("/v/{}", crate::build_info::ASSET_VERSION);
        let mut html = String::from_utf8_lossy(&file.data).into_owned();
        for directory in ["src", "views", "styles", "icons", "vendor"] {
            html = html.replace(
                &format!("\"/{directory}/"),
                &format!("\"{prefix}/{directory}/"),
            );
        }
        let etag = format!("\"{}\"", hex::encode(Sha256::digest(html.as_bytes())));
        file.data = std::borrow::Cow::Owned(html.into_bytes());
        etag
    } else {
        format!("\"{}\"", hex::encode(file.metadata.sha256_hash()))
    };
    let unchanged = request
        .get(header::IF_NONE_MATCH)
        .and_then(|value| value.to_str().ok())
        .is_some_and(|value| {
            value.split(',').any(|tag| {
                let tag = tag.trim();
                tag == "*" || tag.strip_prefix("W/").unwrap_or(tag) == etag
            })
        });
    let length = file.data.len();
    let body = if head || unchanged {
        Body::empty()
    } else {
        match file.data {
            std::borrow::Cow::Borrowed(bytes) => Body::from(bytes),
            std::borrow::Cow::Owned(bytes) => Body::from(bytes),
        }
    };
    let mut response = Response::new(body);
    if unchanged {
        *response.status_mut() = StatusCode::NOT_MODIFIED;
    }
    let mime = if key.ends_with(".js") || key.ends_with(".mjs") {
        "text/javascript; charset=utf-8".to_owned()
    } else if key.ends_with(".md")
        || key
            .rsplit('/')
            .next()
            .is_some_and(|name| name.starts_with("LICENSE") || name == "OFL.txt")
    {
        "text/plain; charset=utf-8".to_owned()
    } else {
        mime_guess::from_path(key)
            .first_or_octet_stream()
            .to_string()
    };
    let headers = response.headers_mut();
    if let Ok(value) = HeaderValue::from_str(&mime) {
        headers.insert(header::CONTENT_TYPE, value);
    }
    if let Ok(value) = HeaderValue::from_str(&etag) {
        headers.insert(header::ETAG, value);
    }
    if !unchanged && let Ok(value) = HeaderValue::from_str(&length.to_string()) {
        headers.insert(header::CONTENT_LENGTH, value);
    }
    headers.insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static(if versioned {
            "public, max-age=31536000, immutable"
        } else {
            "no-cache"
        }),
    );
    headers.insert(header::VARY, HeaderValue::from_static("Accept-Encoding"));
    headers.insert(
        header::X_CONTENT_TYPE_OPTIONS,
        HeaderValue::from_static("nosniff"),
    );
    if key == "views/diagram-renderer.html" {
        headers.insert(
            header::CONTENT_SECURITY_POLICY,
            super::security::diagram_renderer_policy(),
        );
        headers.insert(
            header::X_FRAME_OPTIONS,
            HeaderValue::from_static("SAMEORIGIN"),
        );
    }
    response
}
